# Authour: Bill Van Leeuwen
# Purpose: Configure a Jenkins Build Server
# Tasks:
# - Installs and configures firewalld
# - Installs jenkins

- name: Configure and Install Jenkins
  hosts: all
  become: yes
  become_user: root
  tasks:


  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Install Prerequisite Packages
    ansible.builtin.dnf:
      name: 
        - java-11-openjdk
        - firewalld
        - git


  - name: Download Jenkins
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Get Jenkins GPG Key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  
  - name: Install Jenkins
    ansible.builtin.dnf:
      name: 
        - jenkins


  - name: Add Firewall-cmd To Systemd
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: firewalld
    
  - name: Configure firewalld for jenkins
    ansible.posix.firewalld:
      service: jenkins
      permanent: yes
      state: enabled


  - name: Configure firewalld for http for jenkins
    ansible.posix.firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled

  - name: Open port 8080 for jenkins
    ansible.posix.firewalld:
      port: 8080/tcp
      state: enabled


  - name: Add jenkins To Systemd
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: jenkins

  - name: generate ssh key for Jenkins
    community.crypto.openssh_keypair:
      path: /etc/ssh/jenkinsKey
      owner: jenkins
